### ISSUE TITLE
Not showing GitHub user

### ISSUE THREAD

**Issue by lqez** [zerobased-co/muchtrans#52]
https://github.com/zerobased-co/muchtrans/pull/51 was created by @yous and had been merged well.
But the rendered page displays only an Email, not xe's GitHub account.

As-is:
<img width="385" alt="Screen Shot 2019-07-03 at 11 08 39 PM" src="https://user-images.githubusercontent.com/579366/60598354-85d75a00-9de7-11e9-88ce-759e5a7185ca.png">

To-be:
Display xe's GitHub username with a profile photo.

**Comment by yous** [comment]
It's because the email on my public profile is different from the one I use for commits.

**Comment by lqez** [comment]
@yous Thank you for clarifying.

**Comment by yous** [comment]
But I'd rather my GitHub account to be displayed instead of the email. So if there's a way to do so (without changing the email of public profile), please let me know.

**Comment by lqez** [comment]
@yous You can add additional email addresses via https://help.github.com/en/articles/adding-an-email-address-to-your-github-account

**Comment by lqez** [comment]
@yous And let me know after adding secondary emails. I will try to check it out whether it works or not. Thanks.

**Comment by yous** [comment]
Unfortunately, it's already added to my account. The query maybe search public fields of profiles only.

I found that [`GET /repos/:owner/:repo/commits`](https://developer.github.com/v3/repos/commits/) returns commits with its `'author'` having GitHub username. Also there is [`GET /repos/:owner/:repo/commits/:ref`](https://developer.github.com/v3/repos/commits/#get-a-single-commit), so maybe we can use this instead of querying.
